<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ApplicationManagementController;
use App\Http\Controllers\Admin\AdvancedControlsController;
use App\Http\Controllers\Admin\EnvironmentManagementController;
use App\Http\Controllers\Admin\MasterDataController;
use App\Http\Controllers\Admin\PaymentManagementController;
use App\Http\Controllers\Admin\BackupManagementController;
use App\Http\Controllers\Admin\SlaMetricsController;
use App\Http\Controllers\Admin\SecurityManagementController;
use App\Http\Controllers\Admin\AuditLogsController;
use App\Http\Controllers\Admin\ReportsAnalyticsController;
use App\Http\Controllers\Admin\SupportManagementController;
use App\Http\Controllers\Admin\DocumentManagementController;
use App\Http\Controllers\Admin\NotificationManagementController;
use App\Http\Controllers\Admin\StaticPageController;
use App\Http\Controllers\Admin\PricingPlanManagementController;
use App\Http\Controllers\Admin\SubscriptionManagementController;
use App\Http\Controllers\Admin\BusinessSettingsController;
use App\Http\Controllers\Admin\ContactEnquiryController;
use App\Http\Controllers\Admin\FaqManagementController;
use App\Http\Controllers\Admin\GlobalSearchController;
use App\Http\Controllers\Admin\AdminProfileController;
use App\Http\Controllers\Admin\RegistryManagementController;
use App\Http\Controllers\Admin\TemplateManagementController;
use App\Http\Controllers\Admin\UserManagementController;
use App\Http\Controllers\Applicant\ApplicationTrackingController;
use App\Http\Controllers\Applicant\AuthController as ApplicantAuthController;
use App\Http\Controllers\Applicant\DashboardController as ApplicantDashboardController;
use App\Http\Controllers\Applicant\NotificationController as ApplicantNotificationController;
use App\Http\Controllers\Applicant\PaymentController as ApplicantPaymentController;
use App\Http\Controllers\Applicant\PlanSubscriptionController as ApplicantPlanSubscriptionController;
use App\Http\Controllers\Applicant\ProfileController as ApplicantProfileController;
use App\Http\Controllers\Applicant\RegistrationController as ApplicantRegistrationController;
use App\Http\Controllers\Applicant\RenewalController as ApplicantRenewalController;
use App\Http\Controllers\Applicant\SupportController as ApplicantSupportController;
use App\Http\Controllers\Applicant\TransferController as ApplicantTransferController;
use App\Http\Controllers\PublicSite\AboutController;
use App\Http\Controllers\PublicSite\ContactController;
use App\Http\Controllers\PublicSite\FaqController;
use App\Http\Controllers\PublicSite\HomeController;
use App\Http\Controllers\PublicSite\PageController;
use App\Http\Controllers\PublicSite\PricingController;
use App\Http\Controllers\PublicSite\SubscriptionController;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [AboutController::class, 'index'])->name('about');
Route::get('/faq', [FaqController::class, 'index'])->name('faq');
Route::get('/contact', [ContactController::class, 'index'])->name('contact');
Route::post('/contact', [ContactController::class, 'store'])->name('contact.submit');
Route::get('/pricing', [PricingController::class, 'index'])->name('pricing');
Route::get('/pricing/plan/{plan}/subscribe', [SubscriptionController::class, 'show'])->name('pricing.subscribe');
Route::post('/pricing/plan/{plan}/subscribe', [SubscriptionController::class, 'store'])->name('pricing.subscribe.submit');
Route::get('/pages/{slug}', [PageController::class, 'show'])->name('pages.show');

Route::get('/login', [ApplicantAuthController::class, 'showLogin'])->name('applicant.login');
Route::post('/login', [ApplicantAuthController::class, 'login'])->name('applicant.login.submit');
Route::get('/register', [ApplicantAuthController::class, 'showRegister'])->name('register');
Route::post('/register', [ApplicantAuthController::class, 'register'])->name('register.submit');
Route::get('/verify-otp', [ApplicantAuthController::class, 'showVerifyOtp'])->name('applicant.verify-otp');
Route::post('/verify-otp', [ApplicantAuthController::class, 'verifyOtp'])->name('applicant.verify-otp.submit');
Route::get('/forgot-password', [ApplicantAuthController::class, 'showForgotPassword'])->name('applicant.forgot-password');
Route::post('/forgot-password', [ApplicantAuthController::class, 'sendResetLink'])->name('applicant.forgot-password.submit');
Route::get('/reset-password/{token}', [ApplicantAuthController::class, 'showResetPassword'])->name('applicant.reset-password');
Route::post('/reset-password', [ApplicantAuthController::class, 'resetPassword'])->name('applicant.reset-password.submit');

Route::middleware('applicant.auth')->group(function () {
    Route::get('/portal', [ApplicantDashboardController::class, 'index'])->name('applicant.dashboard');
    Route::get('/portal/register/step/{step}', [ApplicantRegistrationController::class, 'step'])->name('applicant.registration.step')->whereNumber('step');
    Route::post('/portal/register/step/{step}', [ApplicantRegistrationController::class, 'save'])->name('applicant.registration.save')->whereNumber('step');
    Route::get('/portal/renewal/step/{step}', [ApplicantRenewalController::class, 'step'])->name('applicant.renewal.step')->whereNumber('step');
    Route::post('/portal/renewal/step/{step}', [ApplicantRenewalController::class, 'save'])->name('applicant.renewal.save')->whereNumber('step');
    Route::get('/portal/transfers', [ApplicantTransferController::class, 'index'])->name('applicant.transfers.index');
    Route::get('/portal/payments', [ApplicantPaymentController::class, 'index'])->name('applicant.payments.index');
    Route::get('/portal/plans/{plan}/subscribe', [ApplicantPlanSubscriptionController::class, 'show'])->name('applicant.plans.subscribe');
    Route::post('/portal/plans/{plan}/subscribe', [ApplicantPlanSubscriptionController::class, 'store'])->name('applicant.plans.subscribe.submit');
    Route::get('/portal/applications', [ApplicationTrackingController::class, 'index'])->name('applicant.applications.index');
    Route::get('/portal/applications/{application}', [ApplicationTrackingController::class, 'show'])->name('applicant.applications.show');
    Route::get('/portal/applications/{application}/clarify', [ApplicationTrackingController::class, 'clarify'])->name('applicant.applications.clarify');
    Route::post('/portal/applications/{application}/clarify', [ApplicationTrackingController::class, 'submitClarification'])->name('applicant.applications.clarify.submit');
    Route::get('/portal/support', [ApplicantSupportController::class, 'index'])->name('applicant.support.index');
    Route::get('/portal/support/create', [ApplicantSupportController::class, 'create'])->name('applicant.support.create');
    Route::post('/portal/support', [ApplicantSupportController::class, 'store'])->name('applicant.support.store');
    Route::get('/portal/support/{ticket}', [ApplicantSupportController::class, 'show'])->name('applicant.support.show');
    Route::post('/portal/support/{ticket}/reply', [ApplicantSupportController::class, 'reply'])->name('applicant.support.reply');
    Route::get('/portal/notifications', [ApplicantNotificationController::class, 'index'])->name('applicant.notifications.index');
    Route::get('/portal/profile', [ApplicantProfileController::class, 'show'])->name('applicant.profile.show');
    Route::post('/portal/profile', [ApplicantProfileController::class, 'update'])->name('applicant.profile.update');
    Route::post('/logout', [ApplicantAuthController::class, 'logout'])->name('applicant.logout');
});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('login', [AuthController::class, 'login'])->name('login.submit');

    Route::middleware('admin.auth')->group(function () {
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
        Route::get('applications/export', [ApplicationManagementController::class, 'export'])->name('applications.export');
        Route::get('applications', [ApplicationManagementController::class, 'index'])->name('applications.index');
        Route::get('applications/{application}/detail', [ApplicationManagementController::class, 'detail'])->name('applications.detail');
        Route::get('applications/{application}', [ApplicationManagementController::class, 'show'])->name('applications.show');
        Route::post('applications/{application}/action', [ApplicationManagementController::class, 'action'])->name('applications.action');
        Route::get('users', [UserManagementController::class, 'index'])->name('users.index');
        Route::get('users/create', [UserManagementController::class, 'create'])->name('users.create');
        Route::post('users', [UserManagementController::class, 'store'])->name('users.store');
        Route::get('users/roles/{role}/permissions', [UserManagementController::class, 'rolePermissions'])->name('users.role.permissions');
        Route::get('payments/export', [PaymentManagementController::class, 'export'])->name('payments.export');
        Route::post('payments/reconcile', [PaymentManagementController::class, 'reconcile'])->name('payments.reconcile');
        Route::get('payments', [PaymentManagementController::class, 'index'])->name('payments.index');
        Route::post('payments/refunds/{refund}/action', [PaymentManagementController::class, 'refundAction'])->name('payments.refund.action');
        Route::get('controls', [AdvancedControlsController::class, 'index'])->name('controls.index');
        Route::post('controls/variables/{variable}', [AdvancedControlsController::class, 'updateVariable'])->name('controls.variable.update');
        Route::post('controls/policies', [AdvancedControlsController::class, 'updatePolicies'])->name('controls.policies.update');
        Route::post('controls/maintenance', [AdvancedControlsController::class, 'toggleMaintenance'])->name('controls.maintenance');
        Route::post('controls/override/arm', [AdvancedControlsController::class, 'armOverride'])->name('controls.override.arm');
        Route::post('controls/override/execute', [AdvancedControlsController::class, 'executeOverride'])->name('controls.override.execute');
        Route::post('controls/sessions/revoke', [AdvancedControlsController::class, 'revokeSessions'])->name('controls.sessions.revoke');
        Route::post('controls/mfa/force', [AdvancedControlsController::class, 'forceMfa'])->name('controls.mfa.force');
        Route::post('controls/export', [AdvancedControlsController::class, 'startExport'])->name('controls.export');
        Route::post('controls/scrub', [AdvancedControlsController::class, 'instantScrub'])->name('controls.scrub');
        Route::get('environment/export', [EnvironmentManagementController::class, 'exportHistory'])->name('environment.export');
        Route::get('environment', [EnvironmentManagementController::class, 'index'])->name('environment.index');
        Route::post('environment/deploy', [EnvironmentManagementController::class, 'triggerDeployment'])->name('environment.deploy');
        Route::post('environment/command', [EnvironmentManagementController::class, 'command'])->name('environment.command');
        Route::post('environment/releases/{release}/action', [EnvironmentManagementController::class, 'releaseAction'])->name('environment.release.action');
        Route::get('master-data/export', [MasterDataController::class, 'exportCountries'])->name('master-data.export');
        Route::get('master-data', [MasterDataController::class, 'index'])->name('master-data.index');
        Route::post('master-data/countries', [MasterDataController::class, 'storeCountry'])->name('master-data.countries.store');
        Route::post('master-data/validation', [MasterDataController::class, 'updateValidation'])->name('master-data.validation');
        Route::post('master-data/dropdown', [MasterDataController::class, 'updateDropdown'])->name('master-data.dropdown');
        Route::get('templates', [TemplateManagementController::class, 'index'])->name('templates.index');
        Route::post('templates/save', [TemplateManagementController::class, 'save'])->name('templates.save');
        Route::post('templates/states', [TemplateManagementController::class, 'storeState'])->name('templates.states.store');
        Route::get('registry', [RegistryManagementController::class, 'index'])->name('registry.index');
        Route::post('registry/save', [RegistryManagementController::class, 'save'])->name('registry.save');
        Route::post('registry/publish', [RegistryManagementController::class, 'publish'])->name('registry.publish');
        Route::post('registry/sandbox', [RegistryManagementController::class, 'sandbox'])->name('registry.sandbox');
        Route::get('backup', [BackupManagementController::class, 'index'])->name('backup.index');
        Route::post('backup/manual', [BackupManagementController::class, 'manualBackup'])->name('backup.manual');
        Route::post('backup/failover', [BackupManagementController::class, 'failover'])->name('backup.failover');
        Route::get('sla', [SlaMetricsController::class, 'index'])->name('sla.index');
        Route::post('sla/triggers', [SlaMetricsController::class, 'updateTriggers'])->name('sla.triggers');
        Route::post('sla/backup-trigger', [SlaMetricsController::class, 'manualTrigger'])->name('sla.backup-trigger');
        Route::post('sla/incidents/{incident}/action', [SlaMetricsController::class, 'incidentAction'])->name('sla.incident.action');
        Route::post('sla/clear-info', [SlaMetricsController::class, 'clearInfoAlerts'])->name('sla.clear-info');
        Route::get('security/export', [SecurityManagementController::class, 'exportReport'])->name('security.export');
        Route::get('security', [SecurityManagementController::class, 'index'])->name('security.index');
        Route::post('security/policy', [SecurityManagementController::class, 'updatePolicy'])->name('security.policy');
        Route::post('security/sync', [SecurityManagementController::class, 'syncProtocols'])->name('security.sync');
        Route::post('security/ip-rules', [SecurityManagementController::class, 'storeIpRule'])->name('security.ip.store');
        Route::delete('security/ip-rules/{rule}', [SecurityManagementController::class, 'deleteIpRule'])->name('security.ip.delete');
        Route::post('security/incidents/{incident}/action', [SecurityManagementController::class, 'incidentAction'])->name('security.incident.action');
        Route::post('security/clear-info', [SecurityManagementController::class, 'clearInfoAlerts'])->name('security.clear-info');
        Route::get('audit/export', [AuditLogsController::class, 'export'])->name('audit.export');
        Route::get('audit/entries/{entry}', [AuditLogsController::class, 'entryDetail'])->name('audit.entry');
        Route::post('audit/sync', [AuditLogsController::class, 'syncTelemetry'])->name('audit.sync');
        Route::get('audit', [AuditLogsController::class, 'index'])->name('audit.index');
        Route::get('reports/export/{type}', [ReportsAnalyticsController::class, 'export'])->name('reports.export');
        Route::get('reports/generated/{report}/download', [ReportsAnalyticsController::class, 'downloadReport'])->name('reports.download');
        Route::delete('reports/generated/{report}', [ReportsAnalyticsController::class, 'deleteReport'])->name('reports.delete');
        Route::post('reports/generated/{report}/regenerate', [ReportsAnalyticsController::class, 'regenerate'])->name('reports.regenerate');
        Route::post('reports/generate', [ReportsAnalyticsController::class, 'generate'])->name('reports.generate');
        Route::post('reports/scheduled', [ReportsAnalyticsController::class, 'toggleScheduled'])->name('reports.scheduled');
        Route::post('reports/period', [ReportsAnalyticsController::class, 'updatePeriod'])->name('reports.period');
        Route::post('reports/refresh', [ReportsAnalyticsController::class, 'refresh'])->name('reports.refresh');
        Route::get('reports', [ReportsAnalyticsController::class, 'index'])->name('reports.index');
        Route::get('support', [SupportManagementController::class, 'index'])->name('support.index');
        Route::get('support/tickets/{ticket}', [SupportManagementController::class, 'ticketDetail'])->name('support.ticket');
        Route::post('support/tickets', [SupportManagementController::class, 'storeTicket'])->name('support.tickets.store');
        Route::post('support/categories', [SupportManagementController::class, 'storeCategory'])->name('support.categories.store');
        Route::post('support/categories/{category}', [SupportManagementController::class, 'updateCategory'])->name('support.categories.update');
        Route::post('support/tickets/{ticket}/message', [SupportManagementController::class, 'sendMessage'])->name('support.message');
        Route::post('support/tickets/{ticket}/note', [SupportManagementController::class, 'addNote'])->name('support.note');
        Route::post('support/tickets/{ticket}/action', [SupportManagementController::class, 'ticketAction'])->name('support.action');
        Route::get('documents', [DocumentManagementController::class, 'index'])->name('documents.index');
        Route::get('documents/items/{document}', [DocumentManagementController::class, 'documentDetail'])->name('documents.detail');
        Route::post('documents/items/{document}/verify', [DocumentManagementController::class, 'verify'])->name('documents.verify');
        Route::post('documents/items/{document}/reject', [DocumentManagementController::class, 'reject'])->name('documents.reject');
        Route::get('notifications', [NotificationManagementController::class, 'index'])->name('notifications.index');
        Route::post('notifications/channel', [NotificationManagementController::class, 'setChannel'])->name('notifications.channel');
        Route::post('notifications/templates', [NotificationManagementController::class, 'storeTemplate'])->name('notifications.templates.store');
        Route::post('notifications/broadcast/draft', [NotificationManagementController::class, 'saveBroadcastDraft'])->name('notifications.broadcast.draft');
        Route::post('notifications/broadcast/execute', [NotificationManagementController::class, 'executeBroadcast'])->name('notifications.broadcast.execute');
        Route::post('notifications/otp', [NotificationManagementController::class, 'updateOtp'])->name('notifications.otp');
        Route::post('notifications/triggers/{trigger}/toggle', [NotificationManagementController::class, 'toggleTrigger'])->name('notifications.triggers.toggle');
        Route::get('static-pages', [StaticPageController::class, 'index'])->name('static-pages.index');
        Route::get('static-pages/create', [StaticPageController::class, 'create'])->name('static-pages.create');
        Route::post('static-pages', [StaticPageController::class, 'store'])->name('static-pages.store');
        Route::get('static-pages/{staticPage}/edit', [StaticPageController::class, 'edit'])->name('static-pages.edit');
        Route::put('static-pages/{staticPage}', [StaticPageController::class, 'update'])->name('static-pages.update');
        Route::delete('static-pages/{staticPage}', [StaticPageController::class, 'destroy'])->name('static-pages.destroy');
        Route::get('business-settings', [BusinessSettingsController::class, 'index'])->name('business-settings.index');
        Route::put('business-settings', [BusinessSettingsController::class, 'update'])->name('business-settings.update');
        Route::get('faq', [FaqManagementController::class, 'index'])->name('faq.index');
        Route::get('faq/create', [FaqManagementController::class, 'create'])->name('faq.create');
        Route::get('faq/{faq}/edit', [FaqManagementController::class, 'edit'])->name('faq.edit');
        Route::post('faq/categories', [FaqManagementController::class, 'storeCategory'])->name('faq.categories.store');
        Route::put('faq/categories/{category}', [FaqManagementController::class, 'updateCategory'])->name('faq.categories.update');
        Route::delete('faq/categories/{category}', [FaqManagementController::class, 'destroyCategory'])->name('faq.categories.destroy');
        Route::post('faq', [FaqManagementController::class, 'store'])->name('faq.store');
        Route::put('faq/{faq}', [FaqManagementController::class, 'update'])->name('faq.update');
        Route::delete('faq/{faq}', [FaqManagementController::class, 'destroy'])->name('faq.destroy');
        Route::get('contact-enquiries', [ContactEnquiryController::class, 'index'])->name('contact-enquiries.index');
        Route::put('contact-enquiries/{submission}', [ContactEnquiryController::class, 'update'])->name('contact-enquiries.update');
        Route::delete('contact-enquiries/{submission}', [ContactEnquiryController::class, 'destroy'])->name('contact-enquiries.destroy');
        Route::get('subscriptions', [SubscriptionManagementController::class, 'index'])->name('subscriptions.index');
        Route::get('subscriptions/create', [SubscriptionManagementController::class, 'create'])->name('subscriptions.create');
        Route::post('subscriptions', [SubscriptionManagementController::class, 'store'])->name('subscriptions.store');
        Route::get('subscriptions/{subscription}/edit', [SubscriptionManagementController::class, 'edit'])->name('subscriptions.edit');
        Route::put('subscriptions/{subscription}', [SubscriptionManagementController::class, 'update'])->name('subscriptions.update');
        Route::get('pricing-plans/create', [PricingPlanManagementController::class, 'create'])->name('pricing-plans.create');
        Route::get('pricing-plans/{plan}/edit', [PricingPlanManagementController::class, 'edit'])->name('pricing-plans.edit');
        Route::post('pricing-plans', [PricingPlanManagementController::class, 'store'])->name('pricing-plans.store');
        Route::put('pricing-plans/{plan}', [PricingPlanManagementController::class, 'update'])->name('pricing-plans.update');
        Route::delete('pricing-plans/{plan}', [PricingPlanManagementController::class, 'destroy'])->name('pricing-plans.destroy');
        Route::get('search/suggest', [GlobalSearchController::class, 'suggest'])->name('search.suggest');
        Route::get('search', [GlobalSearchController::class, 'index'])->name('search');
        Route::get('profile', [AdminProfileController::class, 'show'])->name('profile.show');
        Route::put('profile', [AdminProfileController::class, 'update'])->name('profile.update');
        Route::put('profile/password', [AdminProfileController::class, 'updatePassword'])->name('profile.password');
        Route::post('logout', [AuthController::class, 'logout'])->name('logout');
    });
});
