<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ApplicationManagementController;
use App\Http\Controllers\Admin\AdvancedControlsController;
use App\Http\Controllers\Admin\EnvironmentManagementController;
use App\Http\Controllers\Admin\MasterDataController;
use App\Http\Controllers\Admin\PaymentManagementController;
use App\Http\Controllers\Admin\BackupManagementController;
use App\Http\Controllers\Admin\SlaMetricsController;
use App\Http\Controllers\Admin\SecurityManagementController;
use App\Http\Controllers\Admin\AuditLogsController;
use App\Http\Controllers\Admin\ReportsAnalyticsController;
use App\Http\Controllers\Admin\SupportManagementController;
use App\Http\Controllers\Admin\DocumentManagementController;
use App\Http\Controllers\Admin\NotificationManagementController;
use App\Http\Controllers\Admin\StaticPageController;
use App\Http\Controllers\Admin\BusinessSettingsController;
use App\Http\Controllers\Admin\GlobalSearchController;
use App\Http\Controllers\Admin\AdminProfileController;
use App\Http\Controllers\Admin\RegistryManagementController;
use App\Http\Controllers\Admin\TemplateManagementController;
use App\Http\Controllers\Admin\UserManagementController;
use Illuminate\Support\Facades\Route;

Route::get('/', fn () => redirect()->route('admin.login'));

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('login', [AuthController::class, 'login'])->name('login.submit');

    Route::middleware('admin.auth')->group(function () {
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
        Route::get('applications/export', [ApplicationManagementController::class, 'export'])->name('applications.export');
        Route::get('applications', [ApplicationManagementController::class, 'index'])->name('applications.index');
        Route::get('applications/{application}/detail', [ApplicationManagementController::class, 'detail'])->name('applications.detail');
        Route::get('applications/{application}', [ApplicationManagementController::class, 'show'])->name('applications.show');
        Route::post('applications/{application}/action', [ApplicationManagementController::class, 'action'])->name('applications.action');
        Route::get('users', [UserManagementController::class, 'index'])->name('users.index');
        Route::get('users/create', [UserManagementController::class, 'create'])->name('users.create');
        Route::post('users', [UserManagementController::class, 'store'])->name('users.store');
        Route::get('users/roles/{role}/permissions', [UserManagementController::class, 'rolePermissions'])->name('users.role.permissions');
        Route::get('payments/export', [PaymentManagementController::class, 'export'])->name('payments.export');
        Route::post('payments/reconcile', [PaymentManagementController::class, 'reconcile'])->name('payments.reconcile');
        Route::get('payments', [PaymentManagementController::class, 'index'])->name('payments.index');
        Route::post('payments/refunds/{refund}/action', [PaymentManagementController::class, 'refundAction'])->name('payments.refund.action');
        Route::get('controls', [AdvancedControlsController::class, 'index'])->name('controls.index');
        Route::post('controls/variables/{variable}', [AdvancedControlsController::class, 'updateVariable'])->name('controls.variable.update');
        Route::post('controls/policies', [AdvancedControlsController::class, 'updatePolicies'])->name('controls.policies.update');
        Route::post('controls/maintenance', [AdvancedControlsController::class, 'toggleMaintenance'])->name('controls.maintenance');
        Route::post('controls/override/arm', [AdvancedControlsController::class, 'armOverride'])->name('controls.override.arm');
        Route::post('controls/override/execute', [AdvancedControlsController::class, 'executeOverride'])->name('controls.override.execute');
        Route::post('controls/sessions/revoke', [AdvancedControlsController::class, 'revokeSessions'])->name('controls.sessions.revoke');
        Route::post('controls/mfa/force', [AdvancedControlsController::class, 'forceMfa'])->name('controls.mfa.force');
        Route::post('controls/export', [AdvancedControlsController::class, 'startExport'])->name('controls.export');
        Route::post('controls/scrub', [AdvancedControlsController::class, 'instantScrub'])->name('controls.scrub');
        Route::get('environment/export', [EnvironmentManagementController::class, 'exportHistory'])->name('environment.export');
        Route::get('environment', [EnvironmentManagementController::class, 'index'])->name('environment.index');
        Route::post('environment/deploy', [EnvironmentManagementController::class, 'triggerDeployment'])->name('environment.deploy');
        Route::post('environment/command', [EnvironmentManagementController::class, 'command'])->name('environment.command');
        Route::post('environment/releases/{release}/action', [EnvironmentManagementController::class, 'releaseAction'])->name('environment.release.action');
        Route::get('master-data/export', [MasterDataController::class, 'exportCountries'])->name('master-data.export');
        Route::get('master-data', [MasterDataController::class, 'index'])->name('master-data.index');
        Route::post('master-data/countries', [MasterDataController::class, 'storeCountry'])->name('master-data.countries.store');
        Route::post('master-data/validation', [MasterDataController::class, 'updateValidation'])->name('master-data.validation');
        Route::post('master-data/dropdown', [MasterDataController::class, 'updateDropdown'])->name('master-data.dropdown');
        Route::get('templates', [TemplateManagementController::class, 'index'])->name('templates.index');
        Route::post('templates/save', [TemplateManagementController::class, 'save'])->name('templates.save');
        Route::post('templates/states', [TemplateManagementController::class, 'storeState'])->name('templates.states.store');
        Route::get('registry', [RegistryManagementController::class, 'index'])->name('registry.index');
        Route::post('registry/save', [RegistryManagementController::class, 'save'])->name('registry.save');
        Route::post('registry/publish', [RegistryManagementController::class, 'publish'])->name('registry.publish');
        Route::post('registry/sandbox', [RegistryManagementController::class, 'sandbox'])->name('registry.sandbox');
        Route::get('backup', [BackupManagementController::class, 'index'])->name('backup.index');
        Route::post('backup/manual', [BackupManagementController::class, 'manualBackup'])->name('backup.manual');
        Route::post('backup/failover', [BackupManagementController::class, 'failover'])->name('backup.failover');
        Route::get('sla', [SlaMetricsController::class, 'index'])->name('sla.index');
        Route::post('sla/triggers', [SlaMetricsController::class, 'updateTriggers'])->name('sla.triggers');
        Route::post('sla/backup-trigger', [SlaMetricsController::class, 'manualTrigger'])->name('sla.backup-trigger');
        Route::post('sla/incidents/{incident}/action', [SlaMetricsController::class, 'incidentAction'])->name('sla.incident.action');
        Route::post('sla/clear-info', [SlaMetricsController::class, 'clearInfoAlerts'])->name('sla.clear-info');
        Route::get('security/export', [SecurityManagementController::class, 'exportReport'])->name('security.export');
        Route::get('security', [SecurityManagementController::class, 'index'])->name('security.index');
        Route::post('security/policy', [SecurityManagementController::class, 'updatePolicy'])->name('security.policy');
        Route::post('security/sync', [SecurityManagementController::class, 'syncProtocols'])->name('security.sync');
        Route::post('security/ip-rules', [SecurityManagementController::class, 'storeIpRule'])->name('security.ip.store');
        Route::delete('security/ip-rules/{rule}', [SecurityManagementController::class, 'deleteIpRule'])->name('security.ip.delete');
        Route::post('security/incidents/{incident}/action', [SecurityManagementController::class, 'incidentAction'])->name('security.incident.action');
        Route::post('security/clear-info', [SecurityManagementController::class, 'clearInfoAlerts'])->name('security.clear-info');
        Route::get('audit/export', [AuditLogsController::class, 'export'])->name('audit.export');
        Route::get('audit/entries/{entry}', [AuditLogsController::class, 'entryDetail'])->name('audit.entry');
        Route::post('audit/sync', [AuditLogsController::class, 'syncTelemetry'])->name('audit.sync');
        Route::get('audit', [AuditLogsController::class, 'index'])->name('audit.index');
        Route::get('reports/export/{type}', [ReportsAnalyticsController::class, 'export'])->name('reports.export');
        Route::get('reports/generated/{report}/download', [ReportsAnalyticsController::class, 'downloadReport'])->name('reports.download');
        Route::delete('reports/generated/{report}', [ReportsAnalyticsController::class, 'deleteReport'])->name('reports.delete');
        Route::post('reports/generated/{report}/regenerate', [ReportsAnalyticsController::class, 'regenerate'])->name('reports.regenerate');
        Route::post('reports/generate', [ReportsAnalyticsController::class, 'generate'])->name('reports.generate');
        Route::post('reports/scheduled', [ReportsAnalyticsController::class, 'toggleScheduled'])->name('reports.scheduled');
        Route::post('reports/period', [ReportsAnalyticsController::class, 'updatePeriod'])->name('reports.period');
        Route::post('reports/refresh', [ReportsAnalyticsController::class, 'refresh'])->name('reports.refresh');
        Route::get('reports', [ReportsAnalyticsController::class, 'index'])->name('reports.index');
        Route::get('support', [SupportManagementController::class, 'index'])->name('support.index');
        Route::get('support/tickets/{ticket}', [SupportManagementController::class, 'ticketDetail'])->name('support.ticket');
        Route::post('support/tickets', [SupportManagementController::class, 'storeTicket'])->name('support.tickets.store');
        Route::post('support/categories', [SupportManagementController::class, 'storeCategory'])->name('support.categories.store');
        Route::post('support/categories/{category}', [SupportManagementController::class, 'updateCategory'])->name('support.categories.update');
        Route::post('support/tickets/{ticket}/message', [SupportManagementController::class, 'sendMessage'])->name('support.message');
        Route::post('support/tickets/{ticket}/note', [SupportManagementController::class, 'addNote'])->name('support.note');
        Route::post('support/tickets/{ticket}/action', [SupportManagementController::class, 'ticketAction'])->name('support.action');
        Route::get('documents', [DocumentManagementController::class, 'index'])->name('documents.index');
        Route::get('documents/items/{document}', [DocumentManagementController::class, 'documentDetail'])->name('documents.detail');
        Route::post('documents/items/{document}/verify', [DocumentManagementController::class, 'verify'])->name('documents.verify');
        Route::post('documents/items/{document}/reject', [DocumentManagementController::class, 'reject'])->name('documents.reject');
        Route::get('notifications', [NotificationManagementController::class, 'index'])->name('notifications.index');
        Route::post('notifications/channel', [NotificationManagementController::class, 'setChannel'])->name('notifications.channel');
        Route::post('notifications/templates', [NotificationManagementController::class, 'storeTemplate'])->name('notifications.templates.store');
        Route::post('notifications/broadcast/draft', [NotificationManagementController::class, 'saveBroadcastDraft'])->name('notifications.broadcast.draft');
        Route::post('notifications/broadcast/execute', [NotificationManagementController::class, 'executeBroadcast'])->name('notifications.broadcast.execute');
        Route::post('notifications/otp', [NotificationManagementController::class, 'updateOtp'])->name('notifications.otp');
        Route::post('notifications/triggers/{trigger}/toggle', [NotificationManagementController::class, 'toggleTrigger'])->name('notifications.triggers.toggle');
        Route::get('static-pages', [StaticPageController::class, 'index'])->name('static-pages.index');
        Route::get('static-pages/create', [StaticPageController::class, 'create'])->name('static-pages.create');
        Route::post('static-pages', [StaticPageController::class, 'store'])->name('static-pages.store');
        Route::get('static-pages/{staticPage}/edit', [StaticPageController::class, 'edit'])->name('static-pages.edit');
        Route::put('static-pages/{staticPage}', [StaticPageController::class, 'update'])->name('static-pages.update');
        Route::delete('static-pages/{staticPage}', [StaticPageController::class, 'destroy'])->name('static-pages.destroy');
        Route::get('business-settings', [BusinessSettingsController::class, 'index'])->name('business-settings.index');
        Route::put('business-settings', [BusinessSettingsController::class, 'update'])->name('business-settings.update');
        Route::get('search/suggest', [GlobalSearchController::class, 'suggest'])->name('search.suggest');
        Route::get('search', [GlobalSearchController::class, 'index'])->name('search');
        Route::get('profile', [AdminProfileController::class, 'show'])->name('profile.show');
        Route::put('profile', [AdminProfileController::class, 'update'])->name('profile.update');
        Route::put('profile/password', [AdminProfileController::class, 'updatePassword'])->name('profile.password');
        Route::post('logout', [AuthController::class, 'logout'])->name('logout');
    });
});
